CREATE OR REPLACE TABLE
    `devoteam-tech-challenge-456311.baseball.fact_events` AS
SELECT
    GENERATE_UUID() AS eventId,
    e.gameId,
    e.inningNumber,
    e.inningHalf,
    e.inningHalfEventSequenceNumber,
    e.description,
    e.atBatEventSequenceNumber,
    et.eventTypeId,
    e.createdAt,
    e.updatedAt,
    o.outcomeId,
    es.eventStatusId,
    e.hitterId,
    e.pitcherId,
    pt.pitchTypeId,
    e.pitchSpeed,
    e.pitchZone,
    e.pitcherPitchCount,
    e.hitterPitchCount,
    e.hitLocation,
    e.hitType,
    e.startingBalls,
    e.startingStrikes,
    e.startingOuts,
    e.balls,
    e.strikes,
    e.outs,
    e.is_ab,
    e.is_ab_over,
    e.is_hit,
    e.is_on_base,
    e.is_bunt,
    e.is_bunt_shown,
    e.is_double_play,
    e.is_triple_play,
    e.is_wild_pitch,
    e.is_passed_ball,
    e.homeFinalRunsForInning,
    e.awayFinalRunsForInning,
    e.homeCurrentTotalRuns,
    e.awayCurrentTotalRuns,
    e.lineupTeamId,
    e.lineupPlayerId,
    e.lineupPosition,
    e.lineupOrder,
    e.awayFielder1,
    e.awayFielder2,
    e.awayFielder3,
    e.awayFielder4,
    e.awayFielder5,
    e.awayFielder6,
    e.awayFielder7,
    e.awayFielder8,
    e.awayFielder9,
    e.awayFielder10,
    e.awayFielder11,
    e.awayFielder12,
    e.awayBatter1,
    e.awayBatter2,
    e.awayBatter3,
    e.awayBatter4,
    e.awayBatter5,
    e.awayBatter6,
    e.awayBatter7,
    e.awayBatter8,
    e.awayBatter9,
    e.homeFielder1,
    e.homeFielder2,
    e.homeFielder3,
    e.homeFielder4,
    e.homeFielder5,
    e.homeFielder6,
    e.homeFielder7,
    e.homeFielder8,
    e.homeFielder9,
    e.homeFielder10,
    e.homeFielder11,
    e.homeFielder12,
    e.homeBatter1,
    e.homeBatter2,
    e.homeBatter3,
    e.homeBatter4,
    e.homeBatter5,
    e.homeBatter6,
    e.homeBatter7,
    e.homeBatter8,
    e.homeBatter9,
    e.rob0_start,
    e.rob0_end,
    e.rob0_isOut,
    e.rob0_outcomeId,
    e.rob0_outcomeDescription,
    e.rob1_start,
    e.rob1_end,
    e.rob1_isOut,
    e.rob1_outcomeId,
    e.rob1_outcomeDescription,
    e.rob2_start,
    e.rob2_end,
    e.rob2_isOut,
    e.rob2_outcomeId,
    e.rob2_outcomeDescription,
    e.rob3_start,
    e.rob3_end,
    e.rob3_isOut,
    e.rob3_outcomeId,
    e.rob3_outcomeDescription,
FROM
    `devoteam-tech-challenge-456311.baseball.stg_events` e
    LEFT JOIN `devoteam-tech-challenge-456311.baseball.dim_event_types` et ON e.eventType = et.eventType
    LEFT JOIN `devoteam-tech-challenge-456311.baseball.dim_outcomes` o ON e.outcomeId = o.outcomeCode
    LEFT JOIN `devoteam-tech-challenge-456311.baseball.dim_event_statuses` es ON e.status = es.eventStatus
    LEFT JOIN `devoteam-tech-challenge-456311.baseball.dim_pitch_types` pt ON e.pitchTypeDescription = pt.pitchTypeDescription
ORDER BY
    gameId,
    inningNumber ASC,
    inningHalf DESC,
    inningHalfEventSequenceNumber ASC,
    atBatEventSequenceNumber ASC